<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit691dd5cd0a2ed7e2e64ca2a315745a19
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'N' => 
        array (
            'Notifications\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'Notifications\\' => 
        array (
            0 => __DIR__ . '/../..' . '/_app',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit691dd5cd0a2ed7e2e64ca2a315745a19::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit691dd5cd0a2ed7e2e64ca2a315745a19::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
